### ISSUE TITLE
python 3 gameplan

### ISSUE THREAD

**Issue by adampbeardsley** [epic-astronomy/LWA_EPIC#11]
We talked about this on a telecon, I'm documenting here.

- [x] Update code in `LWA_EPIC` repo to be py2 *and* py3 compatible (#10). Test identical results.
- [x] Integrate new LSL API (`new-lsl-api` branch, but will likely need to start over after previous PR). Test identical results
- At this point our code should be ready for python3, but only tested with py2.
- [x] As proposed on telecon 6/25, merge the two scripts to create one master script at this point.
- [ ] Switch to `docker-gpu-update` branch of bifrost, test in py3.

**Comment by adampbeardsley** [comment]
Half way there y'all!

**Comment by jaycedowell** [comment]
Just FYI:  `docker-gpu-update` was merged into bifrost July 2020.

**Comment by mkolopanis** [comment]
we're currently running in python 3 with [ibverb-support](/epic-astronomy/bifrost/tree/ibverb-support) branch

**Comment by adampbeardsley** [comment]
I'm closing this... if anyone protests, go ahead and reopen.
