### ISSUE TITLE
Is DFT code deterministic?

### ISSUE THREAD

**Issue by mkolopanis** [epic-astronomy/LWA_EPIC#13]
I ran the DFT code twice from commit f22d93364ebda98ab476483fc95f7bcac6019696 in offline and received differing results from both runs. This is troubling considering the input should have been identical.

command used:
```
python LWA_bifrost_DFT.py --offline --tbnfile=/data5/LWA_SV_data/data_raw/TBN/Jupiter/058161_000086727 --imagesize 64 --imageres 1.79057 --nts 512 --channels 4 --accumulate 50 --ints_per_file 40 --out_dir dft/run_?
```

See attached jupyter notebook output for more information. 
[dft_comparison.pdf](https://github.com/epic-astronomy/LWA_EPIC/files/5228656/dft_comparison.pdf)

**Comment by adampbeardsley** [comment]
This sounds a lot like the bug we fixed in #4. Maybe check that the synchronization lines we added are in fact still there and didn't get bulldozed by a merge at some point?
https://github.com/epic-astronomy/LWA_EPIC/pull/4/files

**Comment by mkolopanis** [comment]
thanks for this. I'll take a look.

**Comment by mkolopanis** [comment]
I will implement this in my script_consolidation branch. Looks like I already did :laughing:  
the two runs are identical at least on commit f7a59d37a7ff8d5fba7bac4eb464f2b66cda77ac
[dft_comparison_update.pdf](https://github.com/epic-astronomy/LWA_EPIC/files/5234540/dft_comparison_update.pdf)
